### ISSUE TITLE
Features to use

### ISSUE THREAD

**Issue by nebi-frame** [lukasmatta/cbfjs#2]
What are the features you're using, you don't seem to address them in readme?

**Comment by lukasmatta** [comment]
Hello,
here is list of used features, I've also added the list to the README. Library is currently outdated and I am planning to update it soon.

* Screen resolution
* Touch support
* Color depth
* Timezone offset
* Font list
* OS name
* OS version
* Mobile device detection
* CPU architecture
* Number of CPU cores
